// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNOVJd4PDHZLCzJ2IXivaYOvtYUlBOQxs',
    appId: '1:220396407434:web:7f59036bbf63d2dbe53b73',
    messagingSenderId: '220396407434',
    projectId: 'todolistapp-a7b89',
    authDomain: 'todolistapp-a7b89.firebaseapp.com',
    storageBucket: 'todolistapp-a7b89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZPtWIK3lLc4qW7JpiHFq8am4L_aUgk6w',
    appId: '1:220396407434:android:901f0efd68598ff5e53b73',
    messagingSenderId: '220396407434',
    projectId: 'todolistapp-a7b89',
    storageBucket: 'todolistapp-a7b89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9p-3hGOq05MRpNNWq22cD8gLyvuZOk6w',
    appId: '1:220396407434:ios:a6b8532d7131f4ffe53b73',
    messagingSenderId: '220396407434',
    projectId: 'todolistapp-a7b89',
    storageBucket: 'todolistapp-a7b89.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9p-3hGOq05MRpNNWq22cD8gLyvuZOk6w',
    appId: '1:220396407434:ios:a6b8532d7131f4ffe53b73',
    messagingSenderId: '220396407434',
    projectId: 'todolistapp-a7b89',
    storageBucket: 'todolistapp-a7b89.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNOVJd4PDHZLCzJ2IXivaYOvtYUlBOQxs',
    appId: '1:220396407434:web:cb3571f0ffdc6cc6e53b73',
    messagingSenderId: '220396407434',
    projectId: 'todolistapp-a7b89',
    authDomain: 'todolistapp-a7b89.firebaseapp.com',
    storageBucket: 'todolistapp-a7b89.appspot.com',
  );
}
